
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mainbotdb
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

telegram:
  bot-username: mainbot
  bot-token: 123456:ABC-DEFGHijklmnopqrstuvwxyz
