
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/maintelegrambot
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

telegram:
  bot-username: mainerp_bot
  bot-token: 7508303339:AAGYiely1V_lKI3uKbTAHVOjVBjcgIWPxHs
